# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "andyw8-acts_as_event_owner"
  s.version = "1.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Danny Burkes", "Andy Waite"]
  s.date = "2013-02-09"
  s.description = "Simple calendar events for any ActiveRecord model"
  s.email = "dburkes@netable.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "LICENSE",
    "README.textile",
    "Rakefile",
    "acts_as_event_owner.gemspec",
    "generators/acts_as_event_owner_migration/USAGE",
    "generators/acts_as_event_owner_migration/acts_as_event_owner_migration_generator.rb",
    "generators/acts_as_event_owner_migration/templates/acts_as_event_owner_migration.rb",
    "lib/acts_as_event_owner.rb",
    "lib/acts_as_event_owner/core.rb",
    "lib/acts_as_event_owner/event_occurrence.rb",
    "lib/acts_as_event_owner/event_specification.rb",
    "lib/acts_as_event_owner/exception.rb",
    "lib/acts_as_event_owner/railtie.rb",
    "lib/acts_as_event_owner/ri_cal_fix.rb",
    "lib/acts_as_event_owner/version.rb",
    "lib/generators/acts_as_event_owner/migration/migration_generator.rb",
    "lib/generators/acts_as_event_owner/migration/templates/active_record/acts_as_event_owner_migration.rb",
    "lib/generators/acts_as_event_owner_migration/USAGE",
    "lib/generators/acts_as_event_owner_migration/acts_as_event_owner_migration_generator.rb",
    "lib/generators/acts_as_event_owner_migration/templates/acts_as_event_owner_migration.rb",
    "lib/tasks/acts_as_event_owner_tasks.rake",
    "rails/init.rb",
    "spec/acts_as_event_owner/core_spec.rb",
    "spec/acts_as_event_owner/event_specification_spec.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb",
    "spec/support/model_builders.rb",
    "spec/support/user.rb"
  ]
  s.homepage = "http://github.com/andyw8/acts_as_event_owner"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Simple calendar events for any ActiveRecord model"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ri_cal>, [">= 0"])
    else
      s.add_dependency(%q<ri_cal>, [">= 0"])
    end
  else
    s.add_dependency(%q<ri_cal>, [">= 0"])
  end
end

